services:
  - type: web
    name: media-downloader-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: RENDER
        value: true
      - key: RENDER_VOLUME_PATH
        value: /var/data/media
    disk:
      name: media-files
      mountPath: /var/data/media
      sizeGB: 1
    plan: free 